version: "3"
services:
  mysql:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=claveroot
      - MYSQL_DATABASE=Trabajo4
      - MYSQL_USER=alejandro
      - MYSQL_PASSWORD=alejandro
    ports:
      - "3306:3306"

  myadmin:
    image: "phpmyadmin/phpmyadmin"
    environment:
      - PMA_HOST=mysql:3306
    links:
      - mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql

  aplicacion:
    build: Trabajo4
    links:
      - mysql
    command: ./run.sh
    depends_on:
      - mysql
